/**
 * SHAPE CATALOG — a big library of ready-made formulas for every creator, browsed via the
 * shape-library window (ui.ts). Entries reuse the creators' own spec fields, so applying one is
 * just "fill the inputs and refresh" — the math still runs through the normal builders.
 *
 * Every entry here is machine-validated (scripts run each through its builder and assert ok), so
 * a catalog click can never produce a parse error or an empty shape. Families that differ only by
 * parameters (torus knots, Lissajous figures, TPMS lattices…) are generated by loops.
 */

export interface RevEntry { name: string; group: string; expr: string; a: number; b: number }
export interface CurveEntry { name: string; group: string; xt: string; yt: string; zt: string; t0: number; t1: number; tube: number }
export interface SurfEntry {
  name: string; group: string; xuv: string; yuv: string; zuv: string;
  u0: number; u1: number; v0: number; v1: number; mode: 'shell' | 'solid'; thickness: number;
}
export interface ImpEntry { name: string; group: string; fxyz: string; size: number }

const TAU = 6.2832;

// ============================================================ f(x) revolution (~52)
export const REV_CATALOG: RevEntry[] = [
  // vessels — A + B·sin keeps every profile safely positive
  { name: 'Vase', group: 'Vessels', expr: '1.1+0.55*sin(0.9*x)', a: 0, b: 6 },
  { name: 'Amphora', group: 'Vessels', expr: '(0.95+0.5*sin(1.15*x+0.4))*(1+0.05*x)', a: 0, b: 5.5 },
  { name: 'Urn', group: 'Vessels', expr: '1.15+0.6*sin(0.75*x+0.7)', a: 0, b: 5 },
  { name: 'Pot', group: 'Vessels', expr: '1.3+0.6*sin(1.6*x-0.5)', a: 0, b: 3.2 },
  { name: 'Pitcher', group: 'Vessels', expr: '0.9+0.5*sin(0.62*x+0.5)', a: 0, b: 6 },
  { name: 'Carafe', group: 'Vessels', expr: '0.85+0.55*sin(1.05*x+2.2)', a: 0, b: 5 },
  { name: 'Beaker', group: 'Vessels', expr: '0.75+0.1*x', a: 0, b: 3 },
  { name: 'Chalice', group: 'Vessels', expr: 'max(0.85-1.1*x, max(0.13, 0.75*(1-exp(-2.2*(x-1.6)))))', a: 0, b: 2.6 },
  { name: 'Jug', group: 'Vessels', expr: '1.05+0.65*sin(0.85*x+3.6)', a: 0, b: 5 },
  { name: 'Flask', group: 'Vessels', expr: '0.35+1.05*exp(-0.6*(x-1.1)^2)', a: 0, b: 4 },
  { name: 'Bottle', group: 'Vessels', expr: 'max(0.28, 1.05*sqrt(max(1-((x-1.15)/1.35)^2,0)))', a: 0, b: 3.6 },
  { name: 'Wine glass', group: 'Vessels', expr: 'max(0.09+0.02*x, 0.95*sqrt(max(1-((x-2.9)/1.05)^2,0)))', a: 0, b: 3.6 },
  // eggs
  { name: 'Egg', group: 'Eggs & fruit', expr: '1.3*sqrt(max(1-((x-1.6)/1.6)^2,0))', a: 0, b: 3.2 },
  { name: 'Tall egg', group: 'Eggs & fruit', expr: '1.05*sqrt(max(1-((x-1.9)/1.9)^2,0))*(1+0.09*x)', a: 0, b: 3.8 },
  { name: 'Hen egg', group: 'Eggs & fruit', expr: '1.1*sqrt(max(1-((x-1.4)/1.4)^2,0))*(1+0.12*(x-1.4))', a: 0, b: 2.8 },
  { name: 'Pear', group: 'Eggs & fruit', expr: '0.62+0.48*sin(1.05*x-1.2)', a: 0, b: 4 },
  { name: 'Gourd', group: 'Eggs & fruit', expr: '0.75+0.55*sin(1.5*x+4.2)', a: 0, b: 4.2 },
  { name: 'Droplet', group: 'Eggs & fruit', expr: '1.35*sqrt(max(x,0))*(1-x/3.2)', a: 0, b: 3.2 },
  { name: 'Onion dome', group: 'Eggs & fruit', expr: '1.35*sqrt(max(1-((x-0.9)/1.35)^2,0))+0.12*exp(-((x-2.5)/0.28)^2)', a: 0, b: 2.9 },
  // spinning tops
  { name: 'Top', group: 'Tops', expr: '1.4*sqrt(max(x,0))*exp(-0.5*x)', a: 0, b: 4 },
  { name: 'Wide top', group: 'Tops', expr: '1.9*sqrt(max(x,0))*exp(-0.75*x)', a: 0, b: 3.2 },
  { name: 'Slim top', group: 'Tops', expr: '1.05*sqrt(max(x,0))*exp(-0.38*x)', a: 0, b: 5 },
  { name: 'Spindle', group: 'Tops', expr: '2.1*x*exp(-1.1*x)', a: 0, b: 3.5 },
  { name: 'Teardrop', group: 'Tops', expr: '1.5*x*max(1-x/3.4,0)^1.5', a: 0, b: 3.4 },
  // bells & hourglasses
  { name: 'Bell', group: 'Bells', expr: '1.75*exp(-0.5*x)+0.16', a: 0, b: 3.6 },
  { name: 'Church bell', group: 'Bells', expr: '1.3*exp(-0.75*x)+0.42', a: 0, b: 3 },
  { name: 'Handbell', group: 'Bells', expr: '1.1*exp(-1.05*x)+0.2', a: 0, b: 2.4 },
  { name: 'Hourglass', group: 'Bells', expr: '0.35*cosh(1.2*(x-2))-0.12', a: 0, b: 4 },
  { name: 'Diabolo', group: 'Bells', expr: '0.28+0.62*abs(x-1.6)', a: 0, b: 3.2 },
  // basics
  { name: 'Sphere', group: 'Basics', expr: 'sqrt(max(2.25-(x-1.5)^2,0))', a: 0, b: 3 },
  { name: 'Dome', group: 'Basics', expr: 'sqrt(max(4-x^2,0))', a: 0, b: 2 },
  { name: 'Cone', group: 'Basics', expr: '0.72*x', a: 0, b: 2.6 },
  { name: 'Cylinder', group: 'Basics', expr: '1', a: 0, b: 2.2 },
  { name: 'Barrel', group: 'Basics', expr: '1.15+0.4*sin(1.0472*x)', a: 0, b: 3 },
  { name: 'Puck', group: 'Basics', expr: '1.7', a: 0, b: 0.5 },
  // ribbed & turned
  { name: 'Beaded column', group: 'Turned', expr: '0.72+0.3*abs(sin(2.2*x))', a: 0, b: 5 },
  { name: 'Ribbed vase', group: 'Turned', expr: '1+0.5*sin(0.8*x)+0.09*sin(7*x)', a: 0, b: 6 },
  { name: 'Bamboo', group: 'Turned', expr: '0.55+0.1*exp(-30*sin(1.3*x)^2)', a: 0, b: 6 },
  { name: 'Screw', group: 'Turned', expr: '0.62+0.16*sin(9*x)', a: 0, b: 4.5 },
  { name: 'Column', group: 'Turned', expr: '0.55+0.06*sin(14*x)', a: 0, b: 6 },
  { name: 'Spool', group: 'Turned', expr: '0.42+0.5*(abs(x-1.1)/1.1)^2.2', a: 0, b: 2.2 },
  { name: 'Yo-yo', group: 'Turned', expr: '0.3+0.62*(abs(x-1.2)/1.2)^0.6', a: 0, b: 2.4 },
  // pieces & props
  { name: 'Pawn', group: 'Props', expr: 'max(0.62-0.85*x, 0.15+0.42*exp(-5.5*(x-1.5)^2))', a: 0, b: 1.95 },
  { name: 'Rook', group: 'Props', expr: 'max(0.62-1.1*x, 0.34+0.11*(sign(x-1.35)+1))', a: 0, b: 1.75 },
  { name: 'Mushroom', group: 'Props', expr: 'max(0.17, 1.15*exp(-3.2*(x-1.55)^2))', a: 0, b: 1.85 },
  { name: 'Bowling pin', group: 'Props', expr: '0.42+0.3*sin(1.55*x+4.35)+0.13*x', a: 0, b: 3.9 },
  { name: 'Rocket', group: 'Props', expr: 'min(0.62, 0.62*sqrt(max((5.2-x)/1.4,0)))', a: 0, b: 5.2 },
  { name: 'Lamp', group: 'Props', expr: '0.7+0.5*sin(1.35*x+0.3)+0.1*sin(4*x)', a: 0, b: 5 },
  // horns
  { name: 'Trumpet', group: 'Horns', expr: '0.16+0.55/(4.45-x)', a: 0, b: 4.2 },
  { name: 'Horn', group: 'Horns', expr: '0.12+0.09*x^2', a: 0, b: 3.4 },
  { name: 'Funnel', group: 'Horns', expr: 'max(0.14, 1.5-0.85*x)', a: 0, b: 2.6 },
];

// ============================================================ parametric curves (~52)
export const CURVE_CATALOG: CurveEntry[] = [
  // springs & coils
  { name: 'Spring', group: 'Springs', xt: '1.1*cos(t)', yt: '0.18*t', zt: '1.1*sin(t)', t0: 0, t1: 25.13, tube: 0.16 },
  { name: 'Tight coil', group: 'Springs', xt: 'cos(t)', yt: '0.085*t', zt: 'sin(t)', t0: 0, t1: 50.27, tube: 0.12 },
  { name: 'Fat spring', group: 'Springs', xt: '1.3*cos(t)', yt: '0.34*t', zt: '1.3*sin(t)', t0: 0, t1: 18.85, tube: 0.28 },
  { name: 'Slinky', group: 'Springs', xt: '1.5*cos(t)', yt: '0.09*t', zt: '1.5*sin(t)', t0: 0, t1: 37.7, tube: 0.09 },
  { name: 'Conical spring', group: 'Springs', xt: '(0.35+0.05*t)*cos(2.2*t)', yt: '0.1*t', zt: '(0.35+0.05*t)*sin(2.2*t)', t0: 0, t1: 27, tube: 0.11 },
  { name: 'Tapered coil', group: 'Springs', xt: '1.35*exp(-0.045*t)*cos(2.6*t)', yt: '0.1*t', zt: '1.35*exp(-0.045*t)*sin(2.6*t)', t0: 0, t1: 27, tube: 0.1 },
  { name: 'Tall helix', group: 'Springs', xt: '0.55*cos(t)', yt: '0.15*t', zt: '0.55*sin(t)', t0: 0, t1: 31.4, tube: 0.12 },
  // toroidal coils
  { name: 'Tokamak', group: 'Springs', xt: '(1.35+0.4*cos(19*t))*cos(t)', yt: '0.4*sin(19*t)', zt: '(1.35+0.4*cos(19*t))*sin(t)', t0: 0, t1: TAU, tube: 0.085 },
  { name: 'Fine tokamak', group: 'Springs', xt: '(1.35+0.32*cos(31*t))*cos(t)', yt: '0.32*sin(31*t)', zt: '(1.35+0.32*cos(31*t))*sin(t)', t0: 0, t1: TAU, tube: 0.07 },
  // spirals
  { name: 'Sphere spiral', group: 'Spirals', xt: '1.5*cos(t)*cos(6*t)', yt: '1.5*sin(t)', zt: '1.5*cos(t)*sin(6*t)', t0: -1.42, t1: 1.42, tube: 0.09 },
  { name: 'Dense sphere spiral', group: 'Spirals', xt: '1.5*cos(t)*cos(10*t)', yt: '1.5*sin(t)', zt: '1.5*cos(t)*sin(10*t)', t0: -1.35, t1: 1.35, tube: 0.08 },
  { name: 'Flat spiral', group: 'Spirals', xt: '(0.25+0.115*t)*cos(t)', yt: '0', zt: '(0.25+0.115*t)*sin(t)', t0: 0, t1: 15.7, tube: 0.09 },
  { name: 'Conical spiral', group: 'Spirals', xt: '(0.15+0.11*t)*cos(2.4*t)', yt: '0.13*t', zt: '(0.15+0.11*t)*sin(2.4*t)', t0: 0, t1: 12, tube: 0.09 },
  // waves & ribbons
  { name: 'Wave', group: 'Waves', xt: 't-3', yt: '0.6*sin(2*t)', zt: '0', t0: 0, t1: 6, tube: 0.2 },
  { name: 'Ribbon wave', group: 'Waves', xt: 't-3', yt: '0.55*sin(2.5*t)', zt: '0.3*cos(5*t)', t0: 0, t1: 6, tube: 0.13 },
  { name: 'Pringle ring', group: 'Waves', xt: '1.3*cos(t)', yt: '0.45*sin(2*t)', zt: '1.3*sin(t)', t0: 0, t1: TAU, tube: 0.16 },
  { name: 'Seam', group: 'Waves', xt: '1.35*cos(t)', yt: '0.62*cos(2*t)', zt: '1.35*sin(t)', t0: 0, t1: TAU, tube: 0.14 },
  { name: 'Crown', group: 'Waves', xt: '1.3*cos(t)', yt: '0.45*sin(4*t)^2', zt: '1.3*sin(t)', t0: 0, t1: TAU, tube: 0.13 },
  { name: 'Orbit', group: 'Waves', xt: '1.5*cos(t)', yt: '0.3*sin(3*t)', zt: '1.1*sin(t)', t0: 0, t1: TAU, tube: 0.13 },
  // wires
  { name: 'Heart wire', group: 'Wires', xt: '1.28*sin(t)^3', yt: '0.08*(13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t))', zt: '0', t0: 0, t1: TAU, tube: 0.11 },
  { name: 'Figure-8', group: 'Wires', xt: '1.5*sin(t)', yt: '0.25*cos(2*t)', zt: '1.5*sin(t)*cos(t)', t0: 0, t1: TAU, tube: 0.13 },
  { name: 'Trefoil (loose)', group: 'Wires', xt: '0.55*(sin(t)+2*sin(2*t))', yt: '0.55*(cos(t)-2*cos(2*t))', zt: '-0.55*sin(3*t)', t0: 0, t1: TAU, tube: 0.22 },
];

// torus-knot family: (p,q) coprime — the tube winds p times around the hole, q times through it
for (const [p, q] of [[2, 3], [2, 5], [2, 7], [2, 9], [3, 4], [3, 5], [3, 7], [3, 8], [4, 5], [4, 7], [5, 6], [5, 7]] as const) {
  CURVE_CATALOG.push({
    name: `Knot (${p},${q})`, group: 'Torus knots',
    xt: `(1.1+0.42*cos(${q}*t))*cos(${p}*t)`, yt: `0.42*sin(${q}*t)`, zt: `(1.1+0.42*cos(${q}*t))*sin(${p}*t)`,
    t0: 0, t1: TAU, tube: 0.13,
  });
}
// Lissajous knots: three perpendicular oscillations
for (const [a, b, c] of [[1, 2, 3], [2, 3, 5], [3, 4, 7], [1, 3, 4], [2, 5, 7], [3, 5, 8], [1, 2, 5], [2, 3, 7], [1, 4, 5]] as const) {
  CURVE_CATALOG.push({
    name: `Lissajous (${a},${b},${c})`, group: 'Lissajous',
    xt: `1.4*sin(${a}*t)`, yt: `1.1*sin(${b}*t+1.5708)`, zt: `1.4*sin(${c}*t)`,
    t0: 0, t1: TAU, tube: 0.1,
  });
}
// flower rings: a ring whose radius (and height) pulses k times
for (const k of [2, 3, 4, 5, 6, 7] as const) {
  CURVE_CATALOG.push({
    name: `Flower (${k})`, group: 'Flowers',
    xt: `(1.25+0.55*cos(${k}*t))*cos(t)`, yt: `0.22*sin(${k}*t)`, zt: `(1.25+0.55*cos(${k}*t))*sin(t)`,
    t0: 0, t1: TAU, tube: 0.12,
  });
}
CURVE_CATALOG.push(
  { name: 'Star ring', group: 'Flowers', xt: '(1.3+0.42*cos(5*t)+0.12*cos(10*t))*cos(t)', yt: '0', zt: '(1.3+0.42*cos(5*t)+0.12*cos(10*t))*sin(t)', t0: 0, t1: TAU, tube: 0.12 },
  { name: 'Wobble ring', group: 'Flowers', xt: '(1.4+0.18*cos(13*t))*cos(t)', yt: '0.12*sin(13*t)', zt: '(1.4+0.18*cos(13*t))*sin(t)', t0: 0, t1: TAU, tube: 0.11 },
);

// Spirographs (hypotrochoid): a pen at radius d on a circle r rolling INSIDE a ring R. Closes after
// r turns for coprime (R,r). Flat in XZ — great for a plate of objects tracing petals.
for (const [R, r, d] of [[5, 3, 5], [7, 3, 4], [7, 4, 5], [8, 3, 5], [5, 2, 3], [9, 4, 6], [11, 5, 6], [13, 6, 7]] as const) {
  const f = `(${R - r}/${r})`;
  CURVE_CATALOG.push({
    name: `Spirograph (${R},${r})`, group: 'Spirographs',
    xt: `${R - r}*cos(t)+${d}*cos(${f}*t)`, yt: '0', zt: `${R - r}*sin(t)-${d}*sin(${f}*t)`,
    t0: 0, t1: TAU * r, tube: 0.08,
  });
}
// Epitrochoids: the pen rides a circle rolling OUTSIDE the ring — looping flower rosettes.
for (const [R, r, d] of [[3, 1, 1], [5, 2, 3], [5, 3, 4], [7, 2, 3], [4, 1, 2]] as const) {
  const f = `(${R + r}/${r})`;
  CURVE_CATALOG.push({
    name: `Epitrochoid (${R},${r})`, group: 'Spirographs',
    xt: `${R + r}*cos(t)-${d}*cos(${f}*t)`, yt: '0', zt: `${R + r}*sin(t)-${d}*sin(${f}*t)`,
    t0: 0, t1: TAU * r, tube: 0.08,
  });
}
// Rose curves r = cos(k·t): k petals when odd, 2k when even. Flat, then a lifted 3D variant.
for (const k of [2, 3, 4, 5, 6, 7, 8] as const) {
  CURVE_CATALOG.push({ name: `Rose (${k})`, group: 'Roses', xt: `cos(${k}*t)*cos(t)`, yt: '0', zt: `cos(${k}*t)*sin(t)`, t0: 0, t1: TAU, tube: 0.07 });
}
for (const k of [3, 5, 7] as const) {
  CURVE_CATALOG.push({ name: `Rose 3D (${k})`, group: 'Roses', xt: `cos(${k}*t)*cos(t)`, yt: `0.4*sin(${k}*t)`, zt: `cos(${k}*t)*sin(t)`, t0: 0, t1: TAU, tube: 0.07 });
}
// classic roulettes & special plane curves (rolling-circle shapes)
CURVE_CATALOG.push(
  { name: 'Cardioid', group: 'Roulettes', xt: '(1-cos(t))*cos(t)', yt: '0', zt: '(1-cos(t))*sin(t)', t0: 0, t1: TAU, tube: 0.1 },
  { name: 'Nephroid', group: 'Roulettes', xt: '3*cos(t)-cos(3*t)', yt: '0', zt: '3*sin(t)-sin(3*t)', t0: 0, t1: TAU, tube: 0.1 },
  { name: 'Deltoid', group: 'Roulettes', xt: '2*cos(t)+cos(2*t)', yt: '0', zt: '2*sin(t)-sin(2*t)', t0: 0, t1: TAU, tube: 0.1 },
  { name: 'Astroid', group: 'Roulettes', xt: 'cos(t)^3', yt: '0', zt: 'sin(t)^3', t0: 0, t1: TAU, tube: 0.1 },
  { name: 'Pentacloid', group: 'Roulettes', xt: '4*cos(t)+cos(4*t)', yt: '0', zt: '4*sin(t)-sin(4*t)', t0: 0, t1: TAU, tube: 0.09 },
  { name: 'Lemniscate', group: 'Roulettes', xt: 'cos(t)/(1+sin(t)^2)', yt: '0', zt: 'sin(t)*cos(t)/(1+sin(t)^2)', t0: 0, t1: TAU, tube: 0.12 },
  { name: 'Butterfly', group: 'Roulettes', xt: 'sin(t)*(exp(cos(t))-2*cos(4*t)-sin(t/12)^5)', yt: '0', zt: 'cos(t)*(exp(cos(t))-2*cos(4*t)-sin(t/12)^5)', t0: 0, t1: 37.7, tube: 0.08 },
);
// 3D flourishes you can build systems around
CURVE_CATALOG.push(
  { name: "Viviani's curve", group: 'Space curves', xt: '1+cos(t)', yt: '2*sin(t/2)', zt: 'sin(t)', t0: 0, t1: 2 * TAU, tube: 0.12 },
  { name: 'Baseball seam', group: 'Space curves', xt: 'cos(t)+0.5*cos(3*t)', yt: '0.6*sin(3*t)', zt: 'sin(t)-0.5*sin(3*t)', t0: 0, t1: TAU, tube: 0.11 },
  { name: 'Helix ribbon', group: 'Space curves', xt: 'cos(t)*(1+0.3*cos(8*t))', yt: '0.14*t', zt: 'sin(t)*(1+0.3*cos(8*t))', t0: 0, t1: 3 * TAU, tube: 0.09 },
  { name: 'Log spiral', group: 'Spirals', xt: 'exp(0.14*t)*cos(t)', yt: '0', zt: 'exp(0.14*t)*sin(t)', t0: 0, t1: 4 * TAU, tube: 0.08 },
  { name: 'Rose spiral', group: 'Spirals', xt: 't*cos(t)*cos(5*t)', yt: '0', zt: 't*sin(t)*cos(5*t)', t0: 0, t1: TAU, tube: 0.07 },
  { name: 'Toroidal spiral', group: 'Spirals', xt: '(2+cos(9*t))*cos(t)', yt: 'sin(9*t)', zt: '(2+cos(9*t))*sin(t)', t0: 0, t1: TAU, tube: 0.08 },
);

// ============================================================ parametric surfaces (~50)
// superellipsoid helper: sign(w)·|w|^p keeps fractional powers real
const sc = (w: string, p: number) => `sign(cos(${w}))*abs(cos(${w}))^${p}`;
const ss = (w: string, p: number) => `sign(sin(${w}))*abs(sin(${w}))^${p}`;
// note: keep p1 ≥ 0.5 — sharper vertical exponents make the poles collapse too slowly for the
// closure detector (the "pole" becomes a tiny ring at the domain's rounded ±π/2 ends)
const superEll = (name: string, p1: number, p2: number, rx: number, ry: number): SurfEntry => ({
  name, group: 'Superellipsoids',
  xuv: `${rx}*${sc('v', p1)}*${sc('u', p2)}`, yuv: `${ry}*${ss('v', p1)}`, zuv: `${rx}*${sc('v', p1)}*${ss('u', p2)}`,
  u0: -3.141593, u1: 3.141593, v0: -1.570796, v1: 1.570796, mode: 'solid', thickness: 0.1,
});

export const SURFACE_CATALOG: SurfEntry[] = [
  // tori
  { name: 'Torus', group: 'Tori', xuv: '(1.3+0.55*cos(v))*cos(u)', yuv: '0.55*sin(v)', zuv: '(1.3+0.55*cos(v))*sin(u)', u0: 0, u1: TAU, v0: 0, v1: TAU, mode: 'solid', thickness: 0.1 },
  { name: 'Slim ring', group: 'Tori', xuv: '(1.55+0.24*cos(v))*cos(u)', yuv: '0.24*sin(v)', zuv: '(1.55+0.24*cos(v))*sin(u)', u0: 0, u1: TAU, v0: 0, v1: TAU, mode: 'solid', thickness: 0.08 },
  { name: 'Fat donut', group: 'Tori', xuv: '(1.05+0.72*cos(v))*cos(u)', yuv: '0.72*sin(v)', zuv: '(1.05+0.72*cos(v))*sin(u)', u0: 0, u1: TAU, v0: 0, v1: TAU, mode: 'solid', thickness: 0.12 },
  { name: 'Wavy gear', group: 'Tori', xuv: '(1.35+0.13*sin(9*u)+0.45*cos(v))*cos(u)', yuv: '0.45*sin(v)', zuv: '(1.35+0.13*sin(9*u)+0.45*cos(v))*sin(u)', u0: 0, u1: TAU, v0: 0, v1: TAU, mode: 'solid', thickness: 0.1 },
  { name: 'Pinched torus', group: 'Tori', xuv: '(0.8+1.1*cos(v))*cos(u)', yuv: '1.1*sin(v)', zuv: '(0.8+1.1*cos(v))*sin(u)', u0: 0, u1: TAU, v0: 0, v1: TAU, mode: 'shell', thickness: 0.09 },
  { name: 'Banana', group: 'Tori', xuv: '(1.35+0.34*cos(v))*cos(u)', yuv: '0.34*sin(v)', zuv: '(1.35+0.34*cos(v))*sin(u)', u0: 0.5, u1: 2.65, v0: 0, v1: TAU, mode: 'shell', thickness: 0.1 },
  // bumpy balls (modulation ∝ sin(k·v) vanishes at the poles, so they stay closed)
  { name: 'Bumpy ball', group: 'Balls', xuv: '(1.2+0.16*sin(6*u)*sin(4*v))*sin(v)*cos(u)', yuv: '(1.2+0.16*sin(6*u)*sin(4*v))*cos(v)', zuv: '(1.2+0.16*sin(6*u)*sin(4*v))*sin(v)*sin(u)', u0: 0, u1: TAU, v0: 0, v1: 3.1416, mode: 'solid', thickness: 0.1 },
  { name: 'Golf ball', group: 'Balls', xuv: '(1.2-0.06*abs(sin(8*u)*sin(6*v)))*sin(v)*cos(u)', yuv: '(1.2-0.06*abs(sin(8*u)*sin(6*v)))*cos(v)', zuv: '(1.2-0.06*abs(sin(8*u)*sin(6*v)))*sin(v)*sin(u)', u0: 0, u1: TAU, v0: 0, v1: 3.1416, mode: 'solid', thickness: 0.1 },
  { name: 'Spiky ball', group: 'Balls', xuv: '(1.1+0.28*sin(7*u)*sin(5*v))*sin(v)*cos(u)', yuv: '(1.1+0.28*sin(7*u)*sin(5*v))*cos(v)', zuv: '(1.1+0.28*sin(7*u)*sin(5*v))*sin(v)*sin(u)', u0: 0, u1: TAU, v0: 0, v1: 3.1416, mode: 'solid', thickness: 0.1 },
  { name: 'Hollow ball', group: 'Balls', xuv: '1.3*sin(v)*cos(u)', yuv: '1.3*cos(v)', zuv: '1.3*sin(v)*sin(u)', u0: 0, u1: TAU, v0: 0, v1: 3.1416, mode: 'shell', thickness: 0.12 },
  { name: 'Rugby ball', group: 'Balls', xuv: '0.9*sin(v)*cos(u)', yuv: '1.55*cos(v)', zuv: '0.9*sin(v)*sin(u)', u0: 0, u1: TAU, v0: 0, v1: 3.1416, mode: 'solid', thickness: 0.1 },
  { name: 'Saucer', group: 'Balls', xuv: '1.6*sin(v)*cos(u)', yuv: '0.55*cos(v)', zuv: '1.6*sin(v)*sin(u)', u0: 0, u1: TAU, v0: 0, v1: 3.1416, mode: 'solid', thickness: 0.1 },
  { name: 'Egg (solid)', group: 'Balls', xuv: '1.05*sin(v)*cos(u)*(1+0.13*cos(v))', yuv: '1.4*cos(v)', zuv: '1.05*sin(v)*sin(u)*(1+0.13*cos(v))', u0: 0, u1: TAU, v0: 0, v1: 3.1416, mode: 'solid', thickness: 0.1 },
  // twisted bands
  { name: 'Möbius', group: 'Bands', xuv: '(1.2+v*cos(u/2))*cos(u)', yuv: 'v*sin(u/2)', zuv: '(1.2+v*cos(u/2))*sin(u)', u0: 0, u1: TAU, v0: -0.45, v1: 0.45, mode: 'shell', thickness: 0.08 },
  { name: 'Möbius (3 twists)', group: 'Bands', xuv: '(1.2+v*cos(3*u/2))*cos(u)', yuv: 'v*sin(3*u/2)', zuv: '(1.2+v*cos(3*u/2))*sin(u)', u0: 0, u1: TAU, v0: -0.4, v1: 0.4, mode: 'shell', thickness: 0.08 },
  { name: 'Möbius (5 twists)', group: 'Bands', xuv: '(1.25+v*cos(5*u/2))*cos(u)', yuv: 'v*sin(5*u/2)', zuv: '(1.25+v*cos(5*u/2))*sin(u)', u0: 0, u1: TAU, v0: -0.35, v1: 0.35, mode: 'shell', thickness: 0.07 },
  { name: 'Twisted band ×2', group: 'Bands', xuv: '(1.25+v*cos(u))*cos(u)', yuv: 'v*sin(u)', zuv: '(1.25+v*cos(u))*sin(u)', u0: 0, u1: TAU, v0: -0.42, v1: 0.42, mode: 'shell', thickness: 0.08 },
  { name: 'Twisted band ×4', group: 'Bands', xuv: '(1.25+v*cos(2*u))*cos(u)', yuv: 'v*sin(2*u)', zuv: '(1.25+v*cos(2*u))*sin(u)', u0: 0, u1: TAU, v0: -0.38, v1: 0.38, mode: 'shell', thickness: 0.08 },
  { name: 'Klein (fig-8)', group: 'Bands', xuv: '(1.1+0.42*cos(u/2)*sin(v)-0.42*sin(u/2)*sin(2*v))*cos(u)', yuv: '0.42*sin(u/2)*sin(v)+0.42*cos(u/2)*sin(2*v)', zuv: '(1.1+0.42*cos(u/2)*sin(v)-0.42*sin(u/2)*sin(2*v))*sin(u)', u0: 0, u1: TAU, v0: 0, v1: TAU, mode: 'shell', thickness: 0.07 },
  // seashells
  { name: 'Conch', group: 'Shells', xuv: '0.75*(2*(1-exp(u/18.85))*cos(u)*cos(v/2)^2)', yuv: '0.75*(1-exp(u/9.42)-sin(v)+exp(u/18.85)*sin(v))', zuv: '0.75*(2*(1-exp(u/18.85))*sin(u)*cos(v/2)^2)', u0: 0, u1: 18.85, v0: 0, v1: TAU, mode: 'shell', thickness: 0.06 },
  { name: 'Snail shell', group: 'Shells', xuv: '0.28*exp(0.11*u)*(1+0.9*cos(v))*cos(u)', yuv: '0.25*exp(0.11*u)*sin(v)-0.06*u', zuv: '0.28*exp(0.11*u)*(1+0.9*cos(v))*sin(u)', u0: 0, u1: 18.85, v0: 0, v1: TAU, mode: 'shell', thickness: 0.06 },
  { name: "Dini's flower", group: 'Shells', xuv: '1.1*cos(u)*sin(v)', yuv: '1.1*(cos(v)+log(tan(v/2)))+0.22*u', zuv: '1.1*sin(u)*sin(v)', u0: 0, u1: 12.566, v0: 0.12, v1: 2, mode: 'shell', thickness: 0.06 },
  { name: 'Cornucopia', group: 'Shells', xuv: 'exp(0.14*u)*cos(u)+exp(0.06*u)*cos(v)*cos(u)', yuv: 'exp(0.06*u)*sin(v)', zuv: 'exp(0.14*u)*sin(u)+exp(0.06*u)*cos(v)*sin(u)', u0: -9.4, u1: 2.4, v0: 0, v1: TAU, mode: 'shell', thickness: 0.06 },
  // minimal-ish classics
  { name: 'Catenoid', group: 'Minimal', xuv: '0.62*cosh(v)*cos(u)', yuv: '0.85*v', zuv: '0.62*cosh(v)*sin(u)', u0: 0, u1: TAU, v0: -1.35, v1: 1.35, mode: 'shell', thickness: 0.08 },
  { name: 'Helicoid', group: 'Minimal', xuv: 'v*cos(u)', yuv: '0.35*u-1.1', zuv: 'v*sin(u)', u0: 0, u1: TAU, v0: -1.3, v1: 1.3, mode: 'shell', thickness: 0.08 },
  { name: 'Spiral ramp', group: 'Minimal', xuv: 'v*cos(u)', yuv: '0.22*u-1.4', zuv: 'v*sin(u)', u0: 0, u1: 12.566, v0: 0.35, v1: 1.35, mode: 'shell', thickness: 0.08 },
  { name: 'Saddle', group: 'Minimal', xuv: 'u', yuv: '0.32*(u^2-v^2)', zuv: 'v', u0: -1.5, u1: 1.5, v0: -1.5, v1: 1.5, mode: 'shell', thickness: 0.09 },
  { name: 'Monkey saddle', group: 'Minimal', xuv: 'u', yuv: '0.25*(u^3-3*u*v^2)', zuv: 'v', u0: -1.3, u1: 1.3, v0: -1.3, v1: 1.3, mode: 'shell', thickness: 0.09 },
  { name: 'Hyperboloid', group: 'Minimal', xuv: '0.55*cosh(v)*cos(u)', yuv: '0.9*sinh(v)', zuv: '0.55*cosh(v)*sin(u)', u0: 0, u1: TAU, v0: -1.3, v1: 1.3, mode: 'shell', thickness: 0.09 },
  { name: 'Cooling tower', group: 'Minimal', xuv: '0.75*cosh(v)*cos(u)', yuv: '1.5*sinh(v/1.6)', zuv: '0.75*cosh(v)*sin(u)', u0: 0, u1: TAU, v0: -1.9, v1: 1.4, mode: 'shell', thickness: 0.09 },
  // sheets
  { name: 'Ripple', group: 'Sheets', xuv: 'u', yuv: '0.35*sin(1.5*u)*cos(1.5*v)', zuv: 'v', u0: -1.8, u1: 1.8, v0: -1.8, v1: 1.8, mode: 'shell', thickness: 0.1 },
  { name: 'Egg carton', group: 'Sheets', xuv: 'u', yuv: '0.4*sin(2*u)*sin(2*v)', zuv: 'v', u0: -1.8, u1: 1.8, v0: -1.8, v1: 1.8, mode: 'shell', thickness: 0.1 },
  { name: 'Sombrero', group: 'Sheets', xuv: 'u', yuv: '0.9*cos(2.4*hypot(u,v))*exp(-0.45*hypot(u,v))', zuv: 'v', u0: -2.6, u1: 2.6, v0: -2.6, v1: 2.6, mode: 'shell', thickness: 0.09 },
  { name: 'Hill', group: 'Sheets', xuv: 'u', yuv: '1.1*exp(-0.8*(u^2+v^2))', zuv: 'v', u0: -2.2, u1: 2.2, v0: -2.2, v1: 2.2, mode: 'shell', thickness: 0.1 },
  { name: 'Flag', group: 'Sheets', xuv: 'u', yuv: '0.3*sin(2.2*u+1.5*v)', zuv: 'v', u0: -1.7, u1: 1.7, v0: -1.1, v1: 1.1, mode: 'shell', thickness: 0.08 },
  { name: 'Dunes', group: 'Sheets', xuv: 'u', yuv: '0.22*sin(2*u)+0.16*sin(3.2*v+1)', zuv: 'v', u0: -2, u1: 2, v0: -2, v1: 2, mode: 'shell', thickness: 0.1 },
  { name: 'Ripple bowl', group: 'Sheets', xuv: 'u', yuv: '0.35*(u^2+v^2)+0.07*sin(5*u)*sin(5*v)', zuv: 'v', u0: -1.6, u1: 1.6, v0: -1.6, v1: 1.6, mode: 'shell', thickness: 0.1 },
  // superellipsoids
  superEll('Dice', 0.5, 0.5, 1.1, 1.1),
  superEll('Pillow', 0.6, 1, 1.25, 0.85),
  superEll('Pinched gem', 2.4, 2.4, 1.25, 1.25),
  superEll('Rounded drum', 0.55, 1, 1.05, 1.05),
  // tubes & cones
  { name: 'Tube', group: 'Tubes', xuv: '1.05*cos(u)', yuv: 'v', zuv: '1.05*sin(u)', u0: 0, u1: TAU, v0: -1.1, v1: 1.1, mode: 'shell', thickness: 0.09 },
  { name: 'Cone shell', group: 'Tubes', xuv: '(0.25+0.5*(v+1.2))*cos(u)', yuv: 'v', zuv: '(0.25+0.5*(v+1.2))*sin(u)', u0: 0, u1: TAU, v0: -1.2, v1: 1.2, mode: 'shell', thickness: 0.09 },
  { name: 'Lampshade', group: 'Tubes', xuv: '(0.75+0.28*v)*cos(u)', yuv: 'v', zuv: '(0.75+0.28*v)*sin(u)', u0: 0, u1: TAU, v0: -0.9, v1: 0.9, mode: 'shell', thickness: 0.08 },
  { name: 'Wavy vase (shell)', group: 'Tubes', xuv: '(1+0.3*sin(1.2*v+0.6)+0.06*sin(5*v))*cos(u)', yuv: 'v', zuv: '(1+0.3*sin(1.2*v+0.6)+0.06*sin(5*v))*sin(u)', u0: 0, u1: TAU, v0: -1.6, v1: 1.6, mode: 'shell', thickness: 0.09 },
  { name: 'Petal disc', group: 'Tubes', xuv: 'v*cos(u)', yuv: '0.22*sin(3*u)*v^2', zuv: 'v*sin(u)', u0: 0, u1: TAU, v0: 0.05, v1: 1.6, mode: 'shell', thickness: 0.08 },
  { name: 'Corkscrew', group: 'Tubes', xuv: '(0.9+0.35*cos(v))*cos(u)', yuv: '0.35*sin(v)+0.24*u-1.5', zuv: '(0.9+0.35*cos(v))*sin(u)', u0: 0, u1: 12.566, v0: 0, v1: TAU, mode: 'shell', thickness: 0.07 },
];

// ============================================================ implicit solids (~50)
// TPMS lattices are infinite — trim each to a ball of radius 2
const tpms = (name: string, f: string): ImpEntry => ({
  name, group: 'Lattices (TPMS)', fxyz: `max(${f}, x^2+y^2+z^2-4)`, size: 2.2,
});

export const IMPLICIT_CATALOG: ImpEntry[] = [
  tpms('Gyroid ball', 'sin(2*x)*cos(2*y)+sin(2*y)*cos(2*z)+sin(2*z)*cos(2*x)+0.35'),
  tpms('Gyroid (thick)', 'sin(2*x)*cos(2*y)+sin(2*y)*cos(2*z)+sin(2*z)*cos(2*x)+0.85'),
  tpms('Gyroid (fine)', 'sin(3*x)*cos(3*y)+sin(3*y)*cos(3*z)+sin(3*z)*cos(3*x)+0.3'),
  tpms('Schwarz P', 'cos(2*x)+cos(2*y)+cos(2*z)+0.35'),
  tpms('Schwarz P (thick)', 'cos(2*x)+cos(2*y)+cos(2*z)+1.1'),
  tpms('Diamond', 'sin(2*x)*sin(2*y)*sin(2*z)+sin(2*x)*cos(2*y)*cos(2*z)+cos(2*x)*sin(2*y)*cos(2*z)+cos(2*x)*cos(2*y)*sin(2*z)+0.25'),
  tpms('Neovius', '3*(cos(2*x)+cos(2*y)+cos(2*z))+4*cos(2*x)*cos(2*y)*cos(2*z)+0.3'),
  tpms('Fischer-Koch', 'cos(4*x)*sin(2*y)*cos(2*z)+cos(2*x)*cos(4*y)*sin(2*z)+sin(2*x)*cos(2*y)*cos(4*z)+0.2'),
  tpms('Lidinoid', '0.5*(sin(4*x)*cos(2*y)*sin(2*z)+sin(4*y)*cos(2*z)*sin(2*x)+sin(4*z)*cos(2*x)*sin(2*y))-0.5*(cos(4*x)*cos(4*y)+cos(4*y)*cos(4*z)+cos(4*z)*cos(4*x))+0.15'),
  // metaballs
  { name: 'Twin blobs', group: 'Metaballs', fxyz: '1 - 0.85/((x-0.8)^2+y^2+z^2+0.05) - 0.85/((x+0.8)^2+y^2+z^2+0.05)', size: 2.3 },
  { name: 'Metaballs', group: 'Metaballs', fxyz: '1 - 0.9/((x-1)^2+y^2+z^2+0.05) - 0.9/((x+1)^2+y^2+z^2+0.05) - 0.9/(x^2+(y-1.2)^2+z^2+0.05)', size: 2.6 },
  { name: 'Tetra blobs', group: 'Metaballs', fxyz: '1 - 0.7/((x-0.9)^2+(y-0.6)^2+z^2+0.05) - 0.7/((x+0.9)^2+(y-0.6)^2+z^2+0.05) - 0.7/(x^2+(y+0.6)^2+(z-0.9)^2+0.05) - 0.7/(x^2+(y+0.6)^2+(z+0.9)^2+0.05)', size: 2.4 },
  { name: 'Blob chain', group: 'Metaballs', fxyz: '1 - 0.5/((x-1.5)^2+y^2+z^2+0.05) - 0.5/((x-0.5)^2+y^2+z^2+0.05) - 0.5/((x+0.5)^2+y^2+z^2+0.05) - 0.5/((x+1.5)^2+y^2+z^2+0.05)', size: 2.5 },
  { name: 'Blob ring', group: 'Metaballs', fxyz: '1 - 0.55/((x-1.1)^2+y^2+z^2+0.05) - 0.55/((x-0.34)^2+y^2+(z-1.05)^2+0.05) - 0.55/((x+0.89)^2+y^2+(z-0.65)^2+0.05) - 0.55/((x+0.89)^2+y^2+(z+0.65)^2+0.05) - 0.55/((x-0.34)^2+y^2+(z+1.05)^2+0.05)', size: 2.4 },
  { name: 'Snowman', group: 'Metaballs', fxyz: '1 - 0.95/(x^2+(y+0.9)^2+z^2+0.05) - 0.55/(x^2+(y-0.25)^2+z^2+0.05) - 0.3/(x^2+(y-1.1)^2+z^2+0.05)', size: 2.4 },
  { name: 'Dumbbell', group: 'Metaballs', fxyz: 'min(min((x-1)^2+y^2+z^2-0.36, (x+1)^2+y^2+z^2-0.36), max(y^2+z^2-0.06, abs(x)-1))', size: 1.9 },
  // classic algebraic surfaces
  { name: 'Heart', group: 'Algebraic', fxyz: '(x^2+9/4*z^2+y^2-1)^3 - x^2*y^3 - 9/80*z^2*y^3', size: 1.4 },
  { name: 'Tangle cube', group: 'Algebraic', fxyz: 'x^4-5*x^2+y^4-5*y^2+z^4-5*z^2+11.8', size: 2.9 },
  { name: 'Pretzel', group: 'Algebraic', fxyz: '(x^2*(1.21-x^2)-y^2)^2 + 0.5*z^2 - 0.02', size: 1.5 },
  { name: 'Chair', group: 'Algebraic', fxyz: '(x^2+y^2+z^2-2.5)^2 - 0.8*((z-1.4)^2-2*x^2)*((z+1.4)^2-2*y^2)', size: 2.4 },
  { name: 'Orthocircles', group: 'Algebraic', fxyz: '((x^2+y^2-1)^2+z^2)*((y^2+z^2-1)^2+x^2)*((z^2+x^2-1)^2+y^2)-0.038', size: 1.6 },
  { name: 'Decocube', group: 'Algebraic', fxyz: '((x^2+y^2-0.64)^2+(z^2-1)^2)*((y^2+z^2-0.64)^2+(x^2-1)^2)*((z^2+x^2-0.64)^2+(y^2-1)^2)-0.03', size: 1.5 },
  // rounded solids
  { name: 'Sphere', group: 'Solids', fxyz: 'x^2+y^2+z^2-1.69', size: 1.5 },
  { name: 'Dice', group: 'Solids', fxyz: 'x^4+y^4+z^4-1.55', size: 1.4 },
  { name: 'Rounded box', group: 'Solids', fxyz: 'x^6+y^6+z^6-1', size: 1.3 },
  { name: 'Octahedron', group: 'Solids', fxyz: 'abs(x)+abs(y)+abs(z)-1.35', size: 1.6 },
  { name: 'Soft octahedron', group: 'Solids', fxyz: 'abs(x)^1.5+abs(y)^1.5+abs(z)^1.5-1.5', size: 1.6 },
  { name: 'Cylinder', group: 'Solids', fxyz: 'max(x^2+z^2-1, abs(y)-0.8)', size: 1.3 },
  { name: 'Capsule', group: 'Solids', fxyz: 'x^2+z^2+max(abs(y)-0.6,0)^2-0.64', size: 1.6 },
  { name: 'Donut', group: 'Solids', fxyz: '(sqrt(x^2+z^2)-1.25)^2+y^2-0.16', size: 1.8 },
  { name: 'Lens', group: 'Solids', fxyz: '(x^2+z^2)/2.6+y^2*3.2-1', size: 1.8 },
  { name: 'Ellipsoid', group: 'Solids', fxyz: 'x^2/2.9+y^2+z^2/1.7-1', size: 1.9 },
  { name: 'Egg (implicit)', group: 'Solids', fxyz: 'x^2+z^2+0.72*y^2*(1+0.16*y)-1', size: 1.7 },
  // CSG playground — min = union, max = intersection, max(a,−b) = subtract
  { name: 'Chain links', group: 'CSG', fxyz: 'min((sqrt(x^2+y^2)-1.05)^2+z^2-0.09, (sqrt((x-1.05)^2+z^2)-1.05)^2+y^2-0.09)', size: 2.3 },
  { name: 'Bead', group: 'CSG', fxyz: 'max(max(x^2+y^2+z^2-1.8, -(x^2+y^2+z^2-1.05)), -(x^2+z^2-0.28))', size: 1.5 },
  { name: 'Cored cube', group: 'CSG', fxyz: 'max(max(max(abs(x)-1,abs(y)-1),abs(z)-1), -(x^2+y^2-0.55))', size: 1.3 },
  { name: 'Jack', group: 'CSG', fxyz: 'min(min(max(max(abs(x)-1.15,abs(y)-0.28),abs(z)-0.28), max(max(abs(y)-1.15,abs(x)-0.28),abs(z)-0.28)), max(max(abs(z)-1.15,abs(x)-0.28),abs(y)-0.28))', size: 1.4 },
  { name: 'Swiss cheese', group: 'CSG', fxyz: 'max(x^2+y^2+z^2-2.1, -min(min((x-0.9)^2+(y-0.5)^2+z^2-0.2, (x+0.9)^2+(y-0.5)^2+z^2-0.2), min(x^2+(y+0.8)^2+(z-0.7)^2-0.2, x^2+(y+0.8)^2+(z+0.7)^2-0.2)))', size: 1.6 },
  { name: 'Dice (cut)', group: 'CSG', fxyz: 'max(x^2+y^2+z^2-1.9, max(max(abs(x)-1.05,abs(y)-1.05),abs(z)-1.05))', size: 1.3 },
  { name: 'Bowl', group: 'CSG', fxyz: 'max(max(x^2+y^2+z^2-1.7, -(x^2+y^2+z^2-1.2)), y-0.15)', size: 1.5 },
  { name: 'Wiffle ball', group: 'CSG', fxyz: 'max(max(x^2+y^2+z^2-1.8, -(x^2+y^2+z^2-1.15)), -min(min(x^2+y^2-0.2, y^2+z^2-0.2), x^2+z^2-0.2))', size: 1.5 },
  // blobby & organic
  { name: 'Blob', group: 'Organic', fxyz: 'x^2+y^2+z^2 - (1.25+0.35*sin(4*x)*sin(4*y)*sin(4*z))^2', size: 1.8 },
  { name: 'Asteroid', group: 'Organic', fxyz: 'x^2+y^2+z^2 - (1.15+0.28*sin(4*x)*sin(3*y)*sin(2*z)+0.15*sin(7*z))^2', size: 1.8 },
  { name: 'Pebble', group: 'Organic', fxyz: '1.4*x^2+2.2*y^2+z^2 - (1.15+0.18*sin(3*x)*sin(2*z))^2', size: 1.7 },
  { name: 'Potato', group: 'Organic', fxyz: 'x^2+1.6*y^2+1.2*z^2 - (1.3+0.25*sin(2*x+1)+0.2*sin(3*z))^2', size: 2 },
  { name: 'Coral', group: 'Organic', fxyz: 'x^2+y^2+z^2 - (1.1+0.2*sin(8*x)*sin(8*y)*sin(8*z))^2', size: 1.7 },
];
